name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
          pip install flake8

      - name: Lint with flake8
        run: |
          flake8 . --max-line-length=120 --exclude=.venv,venv,dist,build

      - name: Run tests with pytest
        run: |
          pytest tests/test_flatten.py --cov=src/flatten_tool/flatten --cov-report=xml

    # - name: Upload coverage report
    #   uses: codecov/codecov-action@v4
    #   with:
    #     file: ./coverage.xml
    #     token: ${{ secrets.CODECOV_TOKEN }} # Optional, set up at codecov.io

  pipx-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install pipx
        run: |
          python -m pip install --user pipx
          python -m pipx ensurepath

      - name: Install flattenify via pipx
        run: |
          python -m pipx install .

      - name: Test flattenify
        run: |
          flatten --help
          flatten examples

# File path: .github/workflows/ci.yml
